### PR TITLE
Revamp travis configuration slightly. Add requirements file.

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Oh dear. Looks like coverage is down quite a bit with this PR.

**Comment by kdesimone** [comment]
the .coveragerc file seems to be ignored.

**Comment by arokem** [comment]
Oh yeah -- I nuked the line that copied it into the test directory. Reinstated!

**Comment by kdesimone** [comment]
thanks for doing this.

by the way—the numpy==1.11 requirement is because of
scipy.signal.spectrogram's not complying with the int/float indexing as of
1.12 onward. This is the easier fix I could come up with, although not
ideal obviously.

**Comment by arokem** [comment]
Let's discuss on a new issue: https://github.com/kdesimone/popeye/issues/56

**Pull request merged**
