### PR TITLE
fixed mx+b orderings; many places in the code this was written as m(x+b)

### PR DESCRIPTION
**Pull request by noahbenson**
In a few tests, I found that some simulated voxels were producing strangely bad fits in popeye; this badness went away when the data were whitened or mean-centered prior to being run through popeye. It ends up that throughout the code, there are places where model predictions are scaled and shifted incorrectly.

Typically, the issue goes like this:
* you use `(m,b) = linregress(something)` to get the scale and shift
* you add the shift: `model += b`
* then you scale: `model *= m`
The problem is that `linregress` returns `(m,b)` for the equation `y = m*x + b`; the formula being used in the code is `y = m*(x + b)`. If the shift (`b`) is significant, this tanks the rest of the fitting.

I **think** that I've fixed all of these in this pull request, but I possibly missed some. I am still learning this repo.

Cheers,
-Noah

### CODE REVIEW

**Comment by noahbenson** [comment]
Looks like there were some tests that failed to produce the right numbers with the pull request; I figure that either:
* I've misinterpreted the whole thing and the original `m(x+b)` is right
* The numbers are not true "gold-standard" values
* There's something else compensating for the `m(x+b)` thing in the code that I've missed?
Any ideas?

**Comment by kdesimone** [comment]
Thanks for all this work.

The coarse grid search estimates are hardset in the tests. In the case of
the fine gradient descent, we can compare the estimated values against the
invented pRF values directly. Rather than figure out which of the grid
search values would be the best, I simply chose hardset values. For example:
https://github.com/kdesimone/popeye/blob/master/popeye/tests/test_og_hrf.py#L78

I'll think more about how to do this formulaically . You could try
commenting out these tests and just see if the final estimate is correct ...

**Comment by psychonomic** [comment]
OK so that's the reason ... I just cloned your fork and ran the tests. It fails on the course grid estimate I link above, but passes the fine searches. I'm going to play around with linspace on the search space and see if I can figure out an a-prior-oriented set of tests to check the grid search estimates.

**Comment by kdesimone** [comment]
The following will work for any pararmeter, except beta and baseline:
`np.linspace(x_grid[0],x_grid[1],Ns)[np.argmin(np.abs(x-np.linspace(x_grid[0],x_grid[1],Ns)))] `

Any suggestion on how to come up with test cases for these in advance?

**Comment by psadil** [comment]
Hi! I'm interested in incorporating `popeye` into out lab's analysis workflows, but the issue of data with nonzero shifts may be problematic. It sounds like this merge is held up because the tests on the ballpark estimates are failing. 

Why are the ballpark estimates tested? Right now, the tests would fail if the coarse grid search ended up producing the exact parameters used to generate the data. It seems like accurate recovery of the parameters with a naive optimization isn't actually a problem.

**Comment by noahbenson** [comment]
I think the merge is held up mostly because I got busy with other stuff and never finished it ;-)
I'm actually looking at this right now... my recollection is that the ballpark tests just need to be smarter about what they expect from the results. I do think we want to continue to test them as a bug in the ballpark search could result in a bug in the overall result.

**Comment by kdesimone** [comment]
This got my attention too. We could just use the approach I suggested [here](https://github.com/kdesimone/popeye/pull/62#issuecomment-510236535), just not test for beta or baseline since these are essentially [ignored](https://github.com/kdesimone/popeye/blob/master/popeye/base.py#L94) during the ballpark fitting.

**Comment by noahbenson** [comment]
> This got my attention too. We could just use the approach I suggested [here](https://github.com/kdesimone/popeye/pull/62#issuecomment-510236535), just not test for beta or baseline since these are essentially [ignored](https://github.com/kdesimone/popeye/blob/master/popeye/base.py#L94) during the ballpark fitting.

Oh, I see--took a bit for me to parse your code into something meaningful in terms of why ballpark fits were failing. Just to check my thinking:
1. The test fails because there are hard-coded expectations of the found-parameters for the ballpark fit (that were generated with the old m(x+b) code--so they are now wrong);
2. the fine search parameters test correctly because all that is necessary in these fits is to compare against the input parameters used to generate the pRF while ignoring the m and b parameters;
3. this approach of testing against the input parameters doesn't work for ballpark because the goal of the ballpark fit is not to end up numerically 'close' to the correct answer; but
4. since the goal of ballpark fit is to end up at the closest grid-position to the correct answer, we can just sort the grid positions for a particular parameter by their distance from the input parameter value and make sure that the found parameter is indeed the closest grid position.

That seems reasonable; though I suspect that for some models and in some cases the closest grid parameter for each dimension individually may not end up correspond to the best grid position. I'll take a shot at implementing it...

**Comment by psadil** [comment]
Cool! @noahbenson beat me to a response (I hope this doesn't read as being pushy for a finished merge; I'm mostly adding my 2 cents to try to help brainstorm :) ). I'll highlight that it seems like it's worth being clear about what it means for the grid search to fail. As mentioned, whether the parameters at the end of the grid search are the closest parameters on the grid to the truth may not matter (especially if the final search recovers the true parameters). E.g., if A) the x and y grid are relatively coarse, B) the true sigma is close to 0, and C) the grid for sigma is fine: you'll get situations where the grid search will settle on a higher sigma because that's the only thing that puts the receptive field close to the truth. But, the final fit can still end up accurate. 

A simpler test could be something like a check that the parameters resulting from the ballpark fit end up as parameters on the expected grid. This would apply only to parameters for which there is a grid (i.e., doing like @kdesimone suggests and ignoring baseline/shift and beta/m). That's less of a test of whether scipy's `optimize.brute` works (hard), and more of a test that `popeye` sets up the grid search correctly for each model.

**Comment by noahbenson** [comment]
Okay, so my previous description missed an additional complication: because the grid-fit doesn't land on a numerically close set of parameters, the baseline and beta (which are not part of the search--rather are determined by regression to the input data at the end) will never be guaranteed to match. Easy way to test them, though, is to rewrite tests like this, where we just make sure that it found the optimal values and used them correctly to rescale the prediction:
```python
# From test_og_fit() in popeye/tests/test_og_hrf.py:
# coarse fit                                                                                                                                                                                            
npt.assert_almost_equal(fit.x0, -5.0)
npt.assert_almost_equal(fit.y0, 5.0)
npt.assert_almost_equal(fit.s0, 2.75)
npt.assert_almost_equal(fit.hrf0, 0.5)
# the baseline/beta should be 0/1 when regressed data vs. estimate
(m,b) = np.polyfit(fit.scaled_ballpark_prediction, data, 1)
npt.assert_almost_equal(m, 1.0)
npt.assert_almost_equal(b, 0.0)
```

This passes for me. It's not a solution to the general problem of how to test the ballpark fits, but it solves the current merge issue and leaves reasonable tests in place. @psadil, I think that part of the goal of the tests is to flag an error when something fundamental to the models/fitting gets changed by an edit, and the tests aren't generated randomly or anything. Because of this, I think it's okay to leave checks against the exact ballpark parameter estimates in place (but, @kdesimone  correct me if I'm wrong).

If I haven't missed anything, and this looks like an okay way to edit the tests, let me know and I'll add it throughout.

**Comment by noahbenson** [comment]
I also seem to be getting an error in `test_dog()`: the final line of the file `npt.assert_almost_equal([fit.theta,fit.rho],[np.arctan2(y,x),np.sqrt(x**2+y**2)], 5)` tests if the `fit.theta` and `fit.rho` (in addition to the `fit.x` and `fit.y`) are close. The problem is that although `x` and `y` are close, the eccentricity is off by 0.00002 or so. Okay if I just turn this down to 4 decimal points?

**Comment by kdesimone** [comment]
Yes that's reasonable.

**Comment by noahbenson** [comment]
Hmm, new the failing error is a numpy version error? They ran on my laptop, but this looks like a change is needed to requirements.txt?

**Comment by kdesimone** [comment]
I'll fix the two auditory model failures once you merge

**Comment by kdesimone** [comment]
Hm the errors are actually different for [2.7](https://travis-ci.org/kdesimone/popeye/jobs/578464331#L382) and [3.6](https://travis-ci.org/kdesimone/popeye/jobs/578464332#L315).

Looks like numpy wants to be 1.13.3.

**Comment by noahbenson** [comment]
I actually have the auditory errors fixed I think; one sec and I'll push them and a requirements.txt change.

**Comment by noahbenson** [comment]
So to fix the fit_auditory_hrf test, I had to use the following test of sigma--the grid fit wasn't actually finding the closest sigma or the one that had been expected, but it is finding one of the two closest sigmas, which this now ensures:
```python
    # at line 77 in test_auditory_hrf.py:
    # test the sigma parameter against best possibility                                                                                                                                                     
    grid_sigmas = np.arange(s_grid.start, s_grid.stop, s_grid.step)
    best_sigma = grid_sigmas[np.argmin(np.abs(grid_sigmas - sigma))]
    npt.assert_array_less(np.abs(fit.sigma0 - sigma), s_grid.step)
```

Also, the requirements.txt explicitly lists `numpy==1.11` --is this a python 2.7 thing? Are there problems if I just set this to `numpy>=1.11`?

**Comment by kdesimone** [comment]
There's probably some long lost historical reason why that was the case.

**Comment by kdesimone** [comment]
Well done.

**Comment by noahbenson** [comment]
Awesome; I don't have write-access so cannot merge, but this is all good as far as I can tell.

**Comment by kdesimone** [comment]
I should issue a new version on pip. I remember that being a gruesome
process. Will revisit that later this evening.

**Comment by noahbenson** [comment]
Yeah, can be a pain. I think that twine has simplified this somewhat though... I'm not an expert, but it looks like you have a source distribution on pypi (not a binary dist, which complicates things). So the process should be something like this:

```bash
> cd code/popeye
# <edit popeye/version.py to have a version numbers like 0.6.0>
> python setup.py sdist
# ... lots of output ...
> twine upload dist/popeye-0.6.0.tar.gz
```
Possibly I am forgetting some configuration details that I did the first time I used twine, but I don't think so.

**Pull request merged**
